version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    #native_passwordはMySQL8.0だとold機能.後でmysqlのバージョンを変えた時に、変更
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      API_DOMAIN: "http://localhost:$FRONT_PORT"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/cooklog
      - gem_data:/usr/local/bundle
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build: 
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        REACT_APP_API_URL: "http://localhost:$API_PORT"
    command: yarn start
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    volumes:
      - ./frontend:/cooklog
    depends_on:
      - api
    stdin_open: true
    tty: true

volumes:
  mysql-data:
  gem_data:
    driver: local
