
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cooklog_development
  pool: 5
  username: kiyomasa
  password: 51830890
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cooklog_test
  pool: 5
  username: kiyomasa
  password: 51830890
  host: localhost
